spring:
  application:
    name: demo
  server:
    port: 8080

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://blogapi-db:3306/blogapi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 57575han
    driver-class-name: org.h2.Driver

  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

  api-docs:
    path: /api-docs

  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
jackson:
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
  time-zone: UTC
app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000
cors:
  allowedOrigins: '*'